version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/VichayanBackEnd/
hooks:
  BeforeInstall:
    - location: scripts/remove-old-revision.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/removefiles.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/deployment.sh
      timeout: 300
      runas: root
